### ISSUE TITLE
Peer Review of Homework 001, Excercise 003 of William-Sparks

### ISSUE THREAD

**Issue by Sparks679** [Sparks679/Stat679Homework#3]
@albenzine

https://github.com/Sparks679/Stat679Homework/commit/c88f59f5539ceeab37d173551e9c8f081460094c

File of Interest: summarizeSNaQresExtend.sh

**Comment by albenzine** [comment]
Upon running the code, everything ran and loaded smoothly. Your comments are very clear and helpful. The set commands are very concise and well-written, so great job! Your read.mes are really helpful for figuring out where to run the codes from. You use if else really well, especially considering we haven't explicitly learned how to embed them in class. You clearly have a strong knowledge of coding; well done!
